export const SET_VALUE_TO_SEARCH = 'SET_VALUE_TO_SEARCH';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_HITS_PER_PAGE = 'SET_HITS_PER_PAGE';
export const SET_PAGE_INDEX = 'SET_PAGE_INDEX';
export const SET_FILTER_FOR_ITEMS_IDS_TO_EXCLUDE =
  'SET_FILTER_FOR_ITEMS_IDS_TO_EXCLUDE';
export const SET_FIELD = 'SET_FIELD';
