export const CREATE_ACCOUNT_TYPE = 'CREATE_ACCOUNT_TYPE';
export const UPDATE_ACCOUNT_TYPE = 'UPDATE_ACCOUNT_TYPE';
export const FETCH_ACCOUNT_TYPE = 'FETCH_ACCOUNT_TYPE';
export const FETCH_ACCOUNT_TYPES = 'FETCH_ACCOUNT_TYPES';
export const DELETE_ACCOUNT_TYPE = 'DELETE_ACCOUNT_TYPE';
