export const CREATE_BOOKING = 'CREATE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const GET_BOOKING = 'GET_BOOKING';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const GET_CUSTOMER_BOOKINGS = 'GET_CUSTOMER_BOOKINGS';
export const GET_CUSTOMER_UNPAID_BOOKINGS = 'GET_CUSTOMER_UNPAID_BOOKINGS';
export const GET_PAYMENT_BOOKINGS_TO_EDIT = 'GET_PAYMENT_BOOKINGS_TO_EDIT';

export const GET_PAYMENT_BOOKINGS = 'GET_PAYMENT_BOOKINGS';
