export const CREATE_EXPENSE = "CREATE_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const GET_EXPENSE = "GET_EXPENSE";
export const GET_EXPENSES = "GET_EXPENSES";
export const GET_VENDOR_EXPENSES = "GET_VENDOR_EXPENSES";
