export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICES = 'GET_INVOICES';
export const GET_CUSTOMER_INVOICES = 'GET_CUSTOMER_INVOICES';
export const GET_CUSTOMER_UNPAID_INVOICES = 'GET_CUSTOMER_UNPAID_INVOICES';
export const GET_PAYMENT_INVOICES_TO_EDIT = 'GET_PAYMENT_INVOICES_TO_EDIT';

export const GET_PAYMENT_INVOICES = 'GET_PAYMENT_INVOICES';
