export const CREATE_ITEM_CATEGORY = 'CREATE_ITEM_CATEGORY';
export const GET_ITEMS_CATEGORIES = 'GET_ITEMS_CATEGORIES';
export const GET_ITEM_CATEGORY = 'GET_ITEM_CATEGORY';
export const EDIT_VEHICLE_CATEGORY = 'EDIT_VEHICLE_CATEGORY';
