export const CREATE_VEHICLE_CATEGORY = 'CREATE_VEHICLE_CATEGORY';
export const GET_VEHICLES_CATEGORIES = 'GET_VEHICLES_CATEGORIES';
export const GET_VEHICLE_CATEGORY = 'GET_VEHICLE_CATEGORY';
export const EDIT_VEHICLE_CATEGORY = 'EDIT_VEHICLE_CATEGORY';
