export const CREATE_MANUAL_JOURNAL = 'CREATE_MANUAL_JOURNAL';
export const UPDATE_MANUAL_JOURNAL = 'UPDATE_MANUAL_JOURNAL';
export const FETCH_MANUAL_JOURNAL = 'FETCH_MANUAL_JOURNAL';
export const FETCH_MANUAL_JOURNALS = 'FETCH_MANUAL_JOURNALS';
export const DELETE_MANUAL_JOURNAL = 'DELETE_MANUAL_JOURNAL';
