export const CREATE_SALE_RECEIPT = 'CREATE_SALE_RECEIPT';
export const UPDATE_SALE_RECEIPT = 'UPDATE_SALE_RECEIPT';
export const DELETE_SALE_RECEIPT = 'DELETE_SALE_RECEIPT';
export const GET_SALE_RECEIPT = 'GET_SALE_RECEIPT';
export const GET_SALE_RECEIPTS = 'GET_SALE_RECEIPTS';
export const GET_CUSTOMER_SALE_RECEIPTS = 'GET_CUSTOMER_SALE_RECEIPTS';
