export const CREATE_SALES_RECEIPT = 'CREATE_SALES_RECEIPT';
export const UPDATE_SALES_RECEIPT = 'UPDATE_SALES_RECEIPT';
export const DELETE_SALES_RECEIPT = 'DELETE_SALES_RECEIPT';
export const GET_SALE_RECEIPT = 'GET_SALE_RECEIPT';
export const GET_SALE_RECEIPTS = 'GET_SALE_RECEIPTS';
export const GET_CUSTOMER_SALE_RECEIPTS = 'GET_CUSTOMER_SALE_RECEIPTS';
