export const CREATE_SALES_RECEIPT = "CREATE_SALES_RECEIPT";
export const UPDATE_SALES_RECEIPT = "UPDATE_SALES_RECEIPT";
export const DELETE_SALES_RECEIPT = "DELETE_SALES_RECEIPT";
export const GET_SALES_RECEIPT = "GET_SALES_RECEIPT";
export const GET_SALES_RECEIPTS = "GET_SALES_RECEIPTS";
export const GET_CUSTOMER_SALES_RECEIPTS = "GET_CUSTOMER_SALES_RECEIPTS";
