export function isSuperAdmin(role) {
  return role === "super_admin";
}

export function isAdmin(role) {
  return role === "admin" || isSuperAdmin(role);
}

export function isManagement(role) {
  return role === "management";
}

const plus = {
  code: 0,
  message: "success",
  expense_preferences: {
    is_mileage_configured: false,
    is_vehicle_configured: false,
    mileage_category_id: "",
    mileage_category_name: "Fuel/Mileage Expenses",
    mileage_rates: [],
    mileage_unit: "km",
    mileage_unit_formatted: "Kilometer(s)",
    vehicles_list: [],
    can_show_employee: false,
    default_markup_percent: "",
    default_markup_percent_formatted: "",
  },
  expense_accounts: [
    {
      account_id: "3039768000000034003",
      account_name: "Cost of Goods Sold",
      account_code: "",
      account_type: "cost_of_goods_sold",
      account_type_formatted: "Cost Of Goods Sold",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000403",
      account_name: "Advertising And Marketing",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000424",
      account_name: "Automobile Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000439",
      account_name: "Bad Debt",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000409",
      account_name: "Bank Fees and Charges",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000454",
      account_name: "Consultant Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000412",
      account_name: "Credit Card Charges",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000451",
      account_name: "Depreciation Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000427",
      account_name: "IT and Internet Expenses",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000433",
      account_name: "Janitorial Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000032023",
      account_name: "Lodging",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000448",
      account_name: "Meals and Entertainment",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000400",
      account_name: "Office Supplies",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000460",
      account_name: "Other Expenses",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000436",
      account_name: "Postage",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000442",
      account_name: "Printing and Stationery",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000072001",
      account_name: "Purchase Discounts",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000430",
      account_name: "Rent Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000457",
      account_name: "Repairs and Maintenance",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000445",
      account_name: "Salaries and Employee Wages",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000421",
      account_name: "Telephone Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000418",
      account_name: "Travel Expense",
      account_code: "",
      account_type: "expense",
      account_type_formatted: "Expense",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000091239",
      account_name: "classical designs",
      account_code: "",
      account_type: "other_current_liability",
      account_type_formatted: "Other Current Liability",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000035003",
      account_name: "Employee Reimbursements",
      account_code: "",
      account_type: "other_current_liability",
      account_type_formatted: "Other Current Liability",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000376",
      account_name: "Tax Payable",
      account_code: "",
      account_type: "other_current_liability",
      account_type_formatted: "Other Current Liability",
      disable_tax: true,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000367",
      account_name: "Furniture and Equipment",
      account_code: "",
      account_type: "fixed_asset",
      account_type_formatted: "Fixed Asset",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000091233",
      account_name: "radios",
      account_code: "",
      account_type: "fixed_asset",
      account_type_formatted: "Fixed Asset",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000000370",
      account_name: "Advance Tax",
      account_code: "",
      account_type: "other_current_asset",
      account_type_formatted: "Other Current Asset",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
    {
      account_id: "3039768000000035001",
      account_name: "Employee Advance",
      account_code: "",
      account_type: "other_current_asset",
      account_type_formatted: "Other Current Asset",
      disable_tax: false,
      is_mileage: false,
      parent_account_id: "",
      parent_account_name: "",
      depth: 0,
      is_disabled_master: false,
    },
  ],
  paidthrough_accounts_list: [
    {
      account_type: "other_current_asset",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Advance Tax",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Other Current Asset",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000000370",
      depth: 0,
      account_type_int: 2,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "other_current_asset",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Employee Advance",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Other Current Asset",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000035001",
      depth: 0,
      account_type_int: 2,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "other_current_asset",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Prepaid Expenses",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Other Current Asset",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000074012",
      depth: 0,
      account_type_int: 2,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "cash",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: true,
      is_accounts_payable: false,
      account_name: "Petty Cash",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Cash",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: true,
      price_precision: 2,
      account_id: "3039768000000000361",
      depth: 0,
      account_type_int: 3,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "cash",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Undeposited Funds",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Cash",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000000358",
      depth: 0,
      account_type_int: 3,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "fixed_asset",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Furniture and Equipment",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Fixed Asset",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000000367",
      depth: 0,
      account_type_int: 6,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "fixed_asset",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "radios",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Fixed Asset",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000091233",
      depth: 0,
      account_type_int: 6,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "other_current_liability",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "classical designs",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Other Current Liability",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000091239",
      depth: 0,
      account_type_int: 8,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "other_current_liability",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Employee Reimbursements",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Other Current Liability",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000035003",
      depth: 0,
      account_type_int: 8,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "equity",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Drawings",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Equity",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000012001",
      depth: 0,
      account_type_int: 13,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "equity",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Opening Balance Offset",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Equity",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000000385",
      depth: 0,
      account_type_int: 13,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "equity",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "Owner's Equity",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: false,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Equity",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000000382",
      depth: 0,
      account_type_int: 13,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
    {
      account_type: "payment_clearing",
      ParentGeneralLedgerName: "",
      gain_or_loss_account: false,
      currency_code: "KES",
      ignore_currency: false,
      is_accounts_payable: false,
      account_name: "classical designsgg",
      schedule_balancesheet_category: "no_category",
      allow_multi_currency: true,
      schedule_profit_and_loss_category: "no_category",
      account_type_formatted: "Payment Clearing Account",
      is_primary_account: false,
      is_accounts_receivable: false,
      is_active: true,
      currency_symbol: "KES",
      masked_account_no: "",
      is_disabled_master: false,
      is_default: false,
      price_precision: 2,
      account_id: "3039768000000091295",
      depth: 0,
      account_type_int: 20,
      account_code: "",
      ParentGeneralLedgerID: "",
      disable_tax: false,
      is_retained_earnings: false,
      currency_id: "3039768000000074082",
    },
  ],
  taxes: [
    {
      tax_specific_type: "tax",
      tax_percentage_formatted: "10",
      is_value_added: true,
      tax_name: "lio",
      tax_authority_id: "",
      input_tax_id: "3039768000000000376",
      is_editable: true,
      tax_id: "3039768000000076001",
      output_tax_id: "3039768000000000376",
      country_code_formatted: "",
      country_code: "",
      deleted: false,
      tax_specific_type_formatted: "Tax",
      tax_type_formatted: "Tax",
      tax_type: "tax",
      tax_percentage: 10.0,
    },
    {
      tax_specific_type: "tax",
      tax_percentage_formatted: "16",
      is_value_added: true,
      tax_name: "vat",
      tax_authority_id: "",
      input_tax_id: "3039768000000000376",
      is_editable: true,
      tax_id: "3039768000000079001",
      output_tax_id: "3039768000000000376",
      country_code_formatted: "",
      country_code: "",
      deleted: false,
      tax_specific_type_formatted: "Tax",
      tax_type_formatted: "Tax",
      tax_type: "tax",
      tax_percentage: 16.0,
    },
  ],
  tax_groups_details: [],
  is_inclusive_tax: false,
  currencies: [
    {
      currency_id: "3039768000000074086",
      currency_code: "AED",
      currency_name: "UAE Dirham",
      currency_name_formatted: "AED- UAE Dirham",
      currency_symbol: "AED",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000105",
      currency_code: "AUD",
      currency_name: "Australian Dollar",
      currency_name_formatted: "AUD- Australian Dollar",
      currency_symbol: "$",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000101",
      currency_code: "CAD",
      currency_name: "Canadian Dollar",
      currency_name_formatted: "CAD- Canadian Dollar",
      currency_symbol: "$",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000113",
      currency_code: "CNY",
      currency_name: "Yuan Renminbi",
      currency_name_formatted: "CNY- Yuan Renminbi",
      currency_symbol: "CNY",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000109",
      currency_code: "EUR",
      currency_name: "Euro",
      currency_name_formatted: "EUR- Euro",
      currency_symbol: "€",
      price_precision: 2,
      currency_format: "1.234.567,89",
      currency_formatter: { decimal_separator: ",", number_separator: "." },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000103",
      currency_code: "GBP",
      currency_name: "Pound Sterling",
      currency_name_formatted: "GBP- Pound Sterling",
      currency_symbol: "£",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000099",
      currency_code: "INR",
      currency_name: "Indian Rupee",
      currency_name_formatted: "INR- Indian Rupee",
      currency_symbol: "Rs.",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000111",
      currency_code: "JPY",
      currency_name: "Japanese Yen",
      currency_name_formatted: "JPY- Japanese Yen",
      currency_symbol: "¥",
      price_precision: 0,
      currency_format: "1,234,567",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000074082",
      currency_code: "KES",
      currency_name: "Kenyan Shilling",
      currency_name_formatted: "KES- Kenyan Shilling",
      currency_symbol: "KES",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: true,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000074084",
      currency_code: "SAR",
      currency_name: "Saudi Riyal",
      currency_name_formatted: "SAR- Saudi Riyal",
      currency_symbol: "SAR",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000097",
      currency_code: "USD",
      currency_name: "United States Dollar",
      currency_name_formatted: "USD- United States Dollar",
      currency_symbol: "$",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
    {
      currency_id: "3039768000000000107",
      currency_code: "ZAR",
      currency_name: "South African Rand",
      currency_name_formatted: "ZAR- South African Rand",
      currency_symbol: "R",
      price_precision: 2,
      currency_format: "1,234,567.89",
      currency_formatter: { decimal_separator: ".", number_separator: "," },
      is_base_currency: false,
      exchange_rate: 0.0,
      effective_date: "",
      effective_date_formatted: "",
    },
  ],
  claimants: [
    {
      claimant_id: "3039768000000074001",
      name: "kibrapassions",
      email: "kibrapassions@gmail.com",
    },
    {
      claimant_id: "3039768000000074198",
      name: "jeff kibra",
      email: "kibzbiz@gmail.com",
    },
  ],
  employees: [],
  today_date: "2022-05-23",
  today_date_formatted: "23 May 2022",
  custom_fields: [],
  entity_fields: [],
  reporting_tags: [],
  previous_vehicle_id: "",
  discount_setting: "percentage",
};